// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jovxopefvldscxrueuma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdnhvcGVmdmxkc2N4cnVldW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Njg5MzQsImV4cCI6MjA2MDA0NDkzNH0.rNVgPhsqS6FIOu_uHw2r8TbeCKJgdMx3XsmF8clQEXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);